---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: image-processor-gpmain
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: image-processor-gpmain
    apis.apps.tanzu.vmware.com/register-api: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  #image: index.docker.io/oawofolu/image-processor-default@sha256:ba3df083e2abf17117488d918ba2321ec7ba9999981077416725cb3f34b09c6e
  params:
    - name: clusterBuilder
      value: full
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: api_descriptor
      value:
        type: openapi
        location:
          path: "/app/static/openapi.json"
          baseUrl: "http://image-processor-api-gp-main.default.${DATA_E2E_BASE_URL}"
        system: image-processors
        owner: team-image-processors
        description: "A set of API endpoints for the ML Image Processing Demo App."
  env:
    - name: MLFLOW_TRACKING_URI
      value: http://mlflow.${DATA_E2E_BASE_URL}
    - name: STREAMLIT_SERVER_ENABLE_STATIC_SERVING
      value: true
    - name: DATA_E2E_MLAPP_GIT_REPO
      value: ${DATA_E2E_MLAPP_GIT_REPO}
    - name: DATA_E2E_MLAPP_GIT_REPO_BRANCH
      value: ${DATA_E2E_MLAPP_GIT_REPO_BRANCH}
    - name: DATA_E2E_MLAPP_INFERENCE_DB_SCHEMA
      value: ${DATA_E2E_MLAPP_INFERENCE_DB_SCHEMA}
  serviceClaims:
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: greenplum-db-claim
    - name: db2
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: postgres-db-claim

  source:
    git:
      url: https://github.com/agapebondservant/ml-image-processing-app.git
      ref:
        branch: gp-main