apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: ml-image-processing-pipeline-app-mri
spec:
  serviceAccountName: default
  fetch:
    - git:
        url: https://github.com/agapebondservant/ml-image-processing-app
        ref: origin/mainmri

  template:
    - ytt:
        paths:
          - config/mri/pipeline.yaml
          - config/mri/values.yaml

  deploy:
    - kapp: {}